// Global Variable Declarations

// player sprite
var player;

// restricts player movement
var movementL = true, movementR = true, movementU = true, movementD = true;

// holds bullet sprite
var bulletImage;

// holds player sprite 
var playerImage;

// holds all bullet sprites generated by player 
var bullets;

// holds all enemy sprites  
var enemies; 

// determines what enemy will spawn
var enemy_spawn;

// holds player score
var score = 0;



// Initialization
function setup() {
    enemy_spawn = random(1,4); 
    createCanvas(800, 1000);
   
 

    player = createSprite(300, 900, 183, 113);
    bulletImage = loadImage("bullet.png");
    playerImage = loadImage("Player.png");
    bullets = new Group();
    enemies = new Group();
    player.addImage(playerImage);
    noCursor();
}

// Main Program Loop
function draw() {
    
    //draws canvas
    background(0, 0, 0);
    
    //draws sprites
    drawSprites();
  
    // draws white, 32pt text on left hand side of screen; displays score
    fill(255,255,255);
    textSize(32);
    text("Score: " + score,10,40);
  
    // randomly determines if an enemy sprite will be generated
    enemy_spawn = random(1,50);
    
    // checks if left arrow is pressed and player is not out of bounds; if not, moves player left
    if (keyIsDown(LEFT_ARROW) && movementL == true) {
        
        player.position.x -= 10;
        
    }
    
    // checks if right arrow is pressed and player is not out of bounds; if not, moves player right
    if (keyIsDown(RIGHT_ARROW) && movementR == true) {
        
        
        player.position.x += 10;
    }
    
   
    
    
    // if the players position exceeds the bounds on the rightside, restrict player movement to the right; if not, allow player to move right
    if (player.position.x > 617) {
        
        movementR = false;
    }else{
        
        movementR = true;
    }

    // if the players position exceeds the bounds on the leftside, restrict player movement to the left; if not, allow player to move left
     if (player.position.x < 5) {
        
        movementL = false;
    }else{
        
        movementL = true;
    }
    
    
    
    // if enter key is pressed, fire bullet
    if (keyWentDown(ENTER)){
        
        // creates bullet sprite
        var bullet = createSprite(player.position.x + 72, player.position.y - 30);
        
        // adds bullet image to sprite
        bullet.addImage(bulletImage);
        
        // sets bullet speed to 10 and sets angle upward
        bullet.setSpeed(10-player.getSpeed(), 270);
        
        // sets the amount of frames that the bullet is shown 
        bullet.life = 60;
        
        // adds bullet instance to bullets group (array)
        bullets.add(bullet);
        
        // prints "fire" to console 
        print("fire");  
        
        
    }
    
    
   
    // checks to see if bullet has hit an enemy sprite; triggers enemyHit function if true
    bullets.collide(enemies, enemyHit);
    
    // if enemy_spawn is 5, a sprite will be generated 
    if (round(enemy_spawn) == 5) {
       
        createEnemy();  
     
       
    }
        
   
    
     
    
}

// Creates Enemy Sprites
function createEnemy() {
        //local variable declarations
    
        // holds enemy image
        var enemyImage;
    
        // generates a number to determine type of enemy
        var enemy_rand = round(random(1,2));
    
        // loads the predetermined image from enemy_rand
        enemyImage = loadImage("pepe" + enemy_rand + ".png");
        
        // determines random x coord for enemy spawning
        var rand = round(random(0, 600))
        
        // creates enemy sprite
        var a = createSprite(rand,0,20,20);
        
        // adds image to enemy sprite
        a.addImage(enemyImage);
    
        // sets square shaped collider 20px by 20px
        a.setCollider("square", 20,20);
    
        // adds enemy instance to enemies group (array)
        enemies.add(a);
    
        //adds 10 speed to enemy, at an 90 degree angle (downward)
        a.addSpeed(10,90);
        
    
        
        
    }

// Removes Bullet and Enemy Sprite, Increments Score By 1
function enemyHit(bullet, enemy) {
    
    // prints "HIT!" to console
    print("HIT!");
    
    // removes bullet that hit enemy sprite
    bullet.remove();
    
    // removes enemy that has been hit by bullet sprite
    enemy.remove();
    
    // increases player score by 1
    score = score + 1;
} 
